package FrontEndApp;


/**
* FrontEndApp/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/xwang/Documents/GitHub/COMP6231Project/src/FE/FrontEnd.idl
* Sunday, July 28, 2019 4:26:07 o'clock PM EDT
*/

public interface FrontEndOperations 
{
  String addEvent (String managerID, String eventID, String eventType, int bookingCapacity);
  String removeEvent (String managerID, String eventID, String eventType);
  String listEventAvailability (String managerID, String eventType);
  String bookEvent (String customerID, String eventID, String eventType);
  String getBookingSchedule (String customerID);
  String cancelEvent (String customerID, String eventID, String eventType);
  String swapEvent (String customerID, String newEventID, String newEventType, String oldEventID, String oldEventType);
} // interface FrontEndOperations
