package FrontEndApp;


/**
* FrontEndApp/FrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/xwang/Documents/GitHub/COMP6231Project/src/FE/FrontEnd.idl
* Sunday, July 28, 2019 4:26:07 o'clock PM EDT
*/

public interface FrontEnd extends FrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEnd
