package FrontEndApp;

/**
* FrontEndApp/FrontEndHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/xwang/Documents/GitHub/COMP6231Project/src/FE/FrontEnd.idl
* Sunday, July 28, 2019 4:26:07 o'clock PM EDT
*/

public final class FrontEndHolder implements org.omg.CORBA.portable.Streamable
{
  public FrontEndApp.FrontEnd value = null;

  public FrontEndHolder ()
  {
  }

  public FrontEndHolder (FrontEndApp.FrontEnd initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FrontEndApp.FrontEndHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FrontEndApp.FrontEndHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FrontEndApp.FrontEndHelper.type ();
  }

}
